services:
  traefik:
    image: "traefik:v2.10"
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8000:8000"
      - "3000:3000"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Accès API Docker en read-only
      - "./traefik.toml:/traefik.toml"  # Fichier de configuration
      - "./acme.json:/letsencrypt/acme.json"  # Stockage des certificats SSL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DOMAIN}`)"  # Accès au dashboard
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"


      - "traefik.http.middlewares.nginx-middleware.addprefix.prefix=/"
      - "traefik.http.middlewares.use-nginx-middleware.chain.middlewares=nginx-middleware"


  nginx-middleware:
    image: nginx:alpine
    container_name: nginx-middleware
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-middleware.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.nginx-middleware.entrypoints=web,websecure"
      - "traefik.http.routers.nginx-middleware.tls.certresolver=myresolver"
      - "traefik.http.services.nginx-middleware.loadbalancer.server.port=80"



networks:
  web:
    name: web

